<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PeasyPilot.Core\PeasyPilot.Core.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.XUnit\PeasyPilot.XUnit.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.Integration\PeasyPilot.Integration.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.BDD\PeasyPilot.BDD.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.Bogus\PeasyPilot.Bogus.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.Moq\PeasyPilot.Moq.csproj" />
    <ProjectReference Include="..\..\src\PeasyPilot.Unit\PeasyPilot.Unit.csproj" />
  </ItemGroup>

</Project>
