using System.Reflection;
using System.Text;

namespace PeasyPilot.Generator;

/// <summary>
/// Generates a test class skeleton for a given type by reflecting on its public
/// constructor and public instance methods: constructor dependencies are mocked
/// (interfaces/abstract types) or faked (concrete types) via PeasyPilot.Moq and
/// PeasyPilot.Bogus, and each public method gets a happy-path test plus one
/// variant per edge case its parameter types expose (nullable, empty string,
/// zero/negative, enum members, empty collection).
/// </summary>
/// <remarks>
/// This is a mechanical, signature-driven scaffold, not a semantic test-case
/// generator: it has no knowledge of the method's actual business behavior, so
/// every generated assertion is a placeholder marked TODO. It saves the
/// boilerplate of wiring dependencies and enumerating type-derived edge cases;
/// it does not replace judgment about what each test should actually verify.
/// </remarks>
public sealed class TestClassScaffolder
{
    /// <summary>
    /// Generates the source code of a test class targeting <paramref name="targetType"/>.
    /// </summary>
    /// <param name="targetType">The type to scaffold tests for.</param>
    /// <param name="framework">Which test framework the output should target.</param>
    /// <param name="targetNamespace">
    /// Namespace for the generated class. Defaults to
    /// <c>{targetType.Namespace}.Tests.Generated</c>.
    /// </param>
    public string GenerateTestClass(Type targetType, TestFrameworkKind framework, string? targetNamespace = null)
    {
        ArgumentNullException.ThrowIfNull(targetType);

        var ctor = targetType.GetConstructors()
            .OrderByDescending(c => c.GetParameters().Length)
            .FirstOrDefault();
        var ctorParams = ctor?.GetParameters() ?? [];

        var methods = targetType
            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(m => !m.IsSpecialName)
            .ToList();

        var ns = targetNamespace ?? $"{targetType.Namespace}.Tests.Generated";
        var className = $"{targetType.Name}Tests";

        var sb = new StringBuilder();

        AppendHeader(sb, targetType, methods.Count);
        AppendUsings(sb, targetType, framework, CollectReferencedNamespaces(ctorParams, methods));
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        AppendClassOpening(sb, className, framework);
        AppendFields(sb, targetType, ctorParams);
        sb.AppendLine();
        AppendSetup(sb, framework, targetType, ctorParams);

        foreach (var method in methods)
        {
            AppendMethodScenarios(sb, method, framework);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, Type targetType, int methodCount)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Scaffolded by PeasyPilot.Generator for {targetType.FullName}.");
        sb.AppendLine("// Mechanical, signature-driven scaffold: constructor dependencies are mocked/faked,");
        sb.AppendLine($"// and each of the {methodCount} public method(s) below gets a happy-path test plus");
        sb.AppendLine("// one variant per edge case its parameter types expose. Every assertion is a TODO");
        sb.AppendLine("// placeholder — this file does not know what the method is actually supposed to do.");
        sb.AppendLine("// Review, fix imports/ambiguous types, replace TODOs, delete scenarios that don't apply.");
        sb.AppendLine("// </auto-generated>");
    }

    private static void AppendUsings(StringBuilder sb, Type targetType, TestFrameworkKind framework, IEnumerable<string> extraNamespaces)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using PeasyPilot.Bogus;");
        sb.AppendLine("using PeasyPilot.Moq;");
        sb.AppendLine("using Assert = PeasyPilot.Core.Extensions.Assert;");

        switch (framework)
        {
            case TestFrameworkKind.XUnit:
                sb.AppendLine("using Xunit;");
                sb.AppendLine("using PeasyPilot.XUnit;");
                break;
            case TestFrameworkKind.NUnit:
                sb.AppendLine("using NUnit.Framework;");
                sb.AppendLine("using PeasyPilot.NUnit;");
                break;
            case TestFrameworkKind.TUnit:
                sb.AppendLine("using global::TUnit;");
                sb.AppendLine("using PeasyPilot.TUnit;");
                break;
        }

        var namespaces = new SortedSet<string>(StringComparer.Ordinal) { targetType.Namespace ?? string.Empty };
        foreach (var ns in extraNamespaces)
        {
            namespaces.Add(ns);
        }

        foreach (var ns in namespaces)
        {
            if (!string.IsNullOrEmpty(ns) && !ns.StartsWith("System", StringComparison.Ordinal))
            {
                sb.AppendLine($"using {ns};");
            }
        }
    }

    private static IEnumerable<string> CollectReferencedNamespaces(ParameterInfo[] ctorParams, List<MethodInfo> methods)
    {
        var seen = new HashSet<string>();

        foreach (var type in ctorParams.Select(p => p.ParameterType)
                     .Concat(methods.SelectMany(m => m.GetParameters().Select(p => p.ParameterType)))
                     .Concat(methods.Select(m => m.ReturnType)))
        {
            foreach (var leaf in LeafTypes(type))
            {
                if (!string.IsNullOrEmpty(leaf.Namespace) && seen.Add(leaf.Namespace))
                {
                    yield return leaf.Namespace;
                }
            }
        }
    }

    private static IEnumerable<Type> LeafTypes(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null)
        {
            foreach (var leaf in LeafTypes(underlying)) yield return leaf;
            yield break;
        }

        if (type.IsArray)
        {
            foreach (var leaf in LeafTypes(type.GetElementType()!)) yield return leaf;
            yield break;
        }

        if (type.IsGenericType)
        {
            foreach (var arg in type.GetGenericArguments())
            {
                foreach (var leaf in LeafTypes(arg)) yield return leaf;
            }

            yield break;
        }

        yield return type;
    }

    private static void AppendClassOpening(StringBuilder sb, string className, TestFrameworkKind framework)
    {
        var baseClass = framework switch
        {
            TestFrameworkKind.XUnit => "PeasyPilotTestBase",
            TestFrameworkKind.NUnit => "PeasyPilotNUnitTestBase",
            TestFrameworkKind.TUnit => "PeasyPilotTUnitTestBase",
            _ => throw new ArgumentOutOfRangeException(nameof(framework))
        };

        sb.AppendLine($"public class {className} : {baseClass}");
        sb.AppendLine("{");
    }

    private static void AppendFields(StringBuilder sb, Type targetType, ParameterInfo[] ctorParams)
    {
        // Not readonly: these are assigned from the framework's async setup hook
        // (InitializeAsync/Setup/BeforeEachAsync), not from a constructor.
        foreach (var param in ctorParams)
        {
            sb.AppendLine($"    private {ParameterScenarios.FormatTypeName(param.ParameterType)} {FieldName(param)} = default!;");
        }

        sb.AppendLine($"    private {ParameterScenarios.FormatTypeName(targetType)} _sut = default!;");
    }

    private static void AppendSetup(StringBuilder sb, TestFrameworkKind framework, Type targetType, ParameterInfo[] ctorParams)
    {
        var assignments = new StringBuilder();
        foreach (var param in ctorParams)
        {
            var plan = ParameterScenarios.Plan(param);
            assignments.AppendLine($"        {FieldName(param)} = {plan.Happy.Expression};");
        }

        var ctorArgs = string.Join(", ", ctorParams.Select(FieldName));
        assignments.AppendLine($"        _sut = new {ParameterScenarios.FormatTypeName(targetType)}({ctorArgs});");

        switch (framework)
        {
            case TestFrameworkKind.XUnit:
                sb.AppendLine("    public override async Task InitializeAsync()");
                sb.AppendLine("    {");
                sb.AppendLine("        await base.InitializeAsync();");
                sb.Append(assignments);
                sb.AppendLine("    }");
                break;
            case TestFrameworkKind.NUnit:
                sb.AppendLine("    [SetUp]");
                sb.AppendLine("    public override void Setup()");
                sb.AppendLine("    {");
                sb.AppendLine("        base.Setup();");
                sb.Append(assignments);
                sb.AppendLine("    }");
                break;
            case TestFrameworkKind.TUnit:
                sb.AppendLine("    public override async ValueTask BeforeEachAsync()");
                sb.AppendLine("    {");
                sb.AppendLine("        await base.BeforeEachAsync();");
                sb.Append(assignments);
                sb.AppendLine("    }");
                break;
        }

        sb.AppendLine();
    }

    private static void AppendMethodScenarios(StringBuilder sb, MethodInfo method, TestFrameworkKind framework)
    {
        var parameters = method.GetParameters();
        var plans = parameters.Select(ParameterScenarios.Plan).ToArray();

        AppendOneScenario(sb, method, framework, "HappyPath", plans.Select(p => p.Happy.Expression).ToArray());

        for (var i = 0; i < parameters.Length; i++)
        {
            foreach (var variant in plans[i].Variants)
            {
                var args = plans.Select(p => p.Happy.Expression).ToArray();
                args[i] = variant.Expression;
                var scenarioName = $"With{PascalCase(parameters[i].Name)}{variant.Suffix}";
                AppendOneScenario(sb, method, framework, scenarioName, args);
            }
        }
    }

    private static void AppendOneScenario(StringBuilder sb, MethodInfo method, TestFrameworkKind framework, string scenarioName, string[] argExpressions)
    {
        var attribute = framework == TestFrameworkKind.XUnit ? "Fact" : "Test";
        var returnType = method.ReturnType;
        var isAsync = typeof(Task).IsAssignableFrom(returnType);
        var isValueTaskAsync = returnType == typeof(ValueTask) || (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(ValueTask<>));
        var hasResult = (isAsync && returnType.IsGenericType) || isValueTaskAsync && returnType.IsGenericType;
        var isVoidLike = returnType == typeof(void) || returnType == typeof(Task) || returnType == typeof(ValueTask);

        var args = string.Join(", ", argExpressions);
        var call = $"_sut.{method.Name}({args})";

        sb.AppendLine($"    [{attribute}]");
        sb.AppendLine($"    public async Task {method.Name}_{scenarioName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Arrange");
        for (var i = 0; i < argExpressions.Length; i++)
        {
            sb.AppendLine($"        var {ArgName(method, i)} = {argExpressions[i]};");
        }

        var argNames = string.Join(", ", Enumerable.Range(0, argExpressions.Length).Select(i => ArgName(method, i)));
        call = $"_sut.{method.Name}({argNames})";

        sb.AppendLine();
        sb.AppendLine("        // Act");
        if (isVoidLike)
        {
            sb.AppendLine((isAsync || isValueTaskAsync ? "        await " : "        ") + call + ";");
        }
        else if (isAsync || isValueTaskAsync)
        {
            sb.AppendLine($"        var result = await {call};");
        }
        else
        {
            sb.AppendLine($"        var result = {call};");
        }

        sb.AppendLine();
        sb.AppendLine("        // Assert");
        if (isVoidLike)
        {
            sb.AppendLine($"        // TODO: assert the expected side effect of {method.Name}.");
        }
        else
        {
            var resultType = hasResult
                ? returnType.GetGenericArguments()[0]
                : returnType;
            var isMeaningfullyNullable = !resultType.IsValueType || Nullable.GetUnderlyingType(resultType) is not null;

            if (isMeaningfullyNullable)
            {
                sb.AppendLine("        Assert.That(result).IsNotNull(); // TODO: replace with a real assertion for this behavior.");
            }
            else
            {
                sb.AppendLine($"        // TODO: assert the expected value of result ({ParameterScenarios.FormatTypeName(resultType)}).");
            }
        }

        if (!isAsync && !isValueTaskAsync)
        {
            sb.AppendLine("        await Task.CompletedTask;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string ArgName(MethodInfo method, int index)
    {
        var param = method.GetParameters()[index];
        return string.IsNullOrEmpty(param.Name) ? $"arg{index}" : param.Name;
    }

    private static string FieldName(ParameterInfo param)
    {
        var name = param.Name ?? "dependency";
        return $"_{name}";
    }

    private static string PascalCase(string? name)
    {
        if (string.IsNullOrEmpty(name)) return "Value";
        return char.ToUpperInvariant(name[0]) + name[1..];
    }
}
